11_SecurityRegistrationAndVoters/lectures_project/begin/src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    use TimestampableEntity;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $author;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likeCount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tags;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(?string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getLikeCount(): ?int
    {
        return $this->likeCount;
    }

    public function setLikeCount(?int $likeCount): self
    {
        $this->likeCount = $likeCount;

        return $this;
    }
    
    public function like()
    {
        $this->likeCount++;
        return $this;
    }
    
    public function dislike()
    {
        $this->likeCount--;
        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
    
    public function getImagePath()
    {
        return 'images/' . $this->getImageFilename();
    }
    
    public function getAuthorAvatarPath()
    {
        return sprintf(
            'https://robohash.org/%s.png?set=set4',
            str_replace(' ', '_', $this->getAuthor())
        );
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }
    
    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
//        $criteria = Criteria::create()
//            ->andWhere(Criteria::expr()->isNull('deletedAt'))
//            ->orderBy(['createdAt' => 'DESC'])
//        ;
//        return $this->comments->matching($criteria);
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }
}

11_SecurityRegistrationAndVoters/lectures_project/begin/src/Controller/Admin/ArticlesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_ADMIN_ARTICLE")
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/admin/articles/create", name="app_admin_articles_create")
     */
    public function create(EntityManagerInterface $em)
    {
        return new Response('Здесь будет страница создания статьи');
    }
}

11_SecurityRegistrationAndVoters/lectures_project/begin/src/Controller/ArticleController.php
<?php

namespace App\Controller;


use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Service\SlackClient;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage(ArticleRepository $repository)
    {
        $articles = $repository->findLatestPublished();
        
        return $this->render('articles/homepage.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/articles/{slug}", name="app_article_show")
     */
    public function show(Article $article, SlackClient $slack)
    {
        if ($article->getSlug() === 'slack') {
           $slack->send('Привет, это важное уведомление!');
        }

        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }
}

11_SecurityRegistrationAndVoters/lectures_project/begin/templates/articles/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-12 col-md-8">

                        <div class="col-sm-12 border rounded-lg overflow-hidden flex-md-row mb-4 shadow-sm position-relative bg-white featured-border">
                            <div class="row">
                                <a class="banner-link" href="#">
                                    <div class="banner-img-block d-block">
                                        <img class="banner-img" src="{{ asset('images/cat-banner1.jpg')}}">
                                    </div>
                                    <h1 class="text-center mt-2 px-4">Спать или не спать: <br>С новыми кроватками это не вопрос</h1>
                                </a>
                            </div>
                        </div>

                        {% for article in articles %}
                        <div class="article-container mb-2">
                            <div class="row no-gutters border rounded-lg overflow-hidden flex-md-row mb-4 shadow-sm position-relative">
                                <div class="col-auto d-none d-lg-block">
                                    <img class="article-img" src="{{ asset(article.imagePath) }}">
                                </div>
                                <a class="col p-2 px-4 d-flex flex-column article-item" href="{{ path('app_article_show', { slug: article.slug}) }}">
                                    <h5 class="mb-2">{{ article.title }} <span class="badge badge-info article-comments">{{ article.nonDeletedComments|length }} комментов</span></h5>
                                    {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                                    <div class="d-flex justify-content-between">
                                        <div class="text-muted align-self-center">
                                            <img
                                                class="article-author-img rounded-circle"
                                                src="{{ article.authorAvatarPath }}"
                                            > {{ article.author }}
                                        </div>
                                        <div class="text-muted align-self-center">{{ article.publishedAt ? article.publishedAt|ago }}</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="col-sm-12 col-md-4 text-center">
                        <div class="bg-white shadow-sm border rounded-lg pb-2 pt-2 px-5 mb-4 featured-border">
                            <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                                <img class="advertisement-img mb-2" src="{{ asset('images/cat-food.jpg')}}">
                                <p><b>Новинка:</b> Лакомные <i class="fas fa-heart text-warning"></i> <i class="fas fa-heart text-info"></i> <i class="fas fa-heart text-danger"></i></p>
                                <button class="btn btn-info">Купить сейчас</button>
                            </div>
                        </div>

                        <div class="quotes-container bg-white shadow-sm border rounded-lg pb-2 pt-2 px-5 featured-border">
                            <h3 class="text-center pb-3">Коты в теме</h3>
                            <p><i class="far fa-comment text-secondary"></i> "Недавно наши ученые создали гудок против собак,
                                другие коты его не слышат, зато собаки уступают дорогу. Наконец-то в лоточек без пробок"
                                <br> — <a href="#">Рыжий Бесстыжий, Антикоррупционер</a></p>

                            <p class="pt-4"><i class="far fa-comment text-secondary"></i> "Этот сайт - это просто прелесть, я влюблена!
                                <i class="fas fa-heart text-danger"></i> <i class="fas fa-heart text-danger"></i> <i class="fas fa-heart text-danger"></i>"
                                <br>— <a href="#">Сметанка, Мурлыкатель</a></p>

                            <p class="pt-4"><i class="far fa-comment text-secondary"></i> "Предлагаю ввести еще темы о еде,
                                например, у меня заготовлены шикарные статьи по сосискам"
                                <br>— <a href="#">Барон Сосискин, Дегустатор сосисок</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

11_SecurityRegistrationAndVoters/lectures_project/begin/templates/articles/show.html.twig
{% extends 'base_content.html.twig' %}

{% block title %}Статья: {{ article.title }}{% endblock %}

{% block content_row_class %}{{ parent() }} no-gutters featured-border{% endblock %}
{% block content_col_class %}{{ parent() }} article-detail{% endblock %}

{% block content %}
    <div class="col-sm-12 p-2">
        <div class="media d-flex align-content-center">
            <img class="article-detail-image align-self-start mr-3 rounded" src="{{ asset(article.imagePath) }}">
            <div class="media-body d-inline-block align-self-center">
                <h1 class="mb-2">{{ article.title }}</h1>
                {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                <div class="d-flex">
                    <div class="text-muted align-self-center">
                        <img
                            class="article-author-img rounded-circle mr-2"
                            src="{{ article.authorAvatarPath }}"
                        >
                        {{ article.author }}
                    </div>
                    <div class="text-muted align-self-center ml-4">{{ article.publishedAt ? article.publishedAt|ago : 'Неопубликована'}}</div>
                    <div
                        class="text-muted align-self-center ml-4 article-detail-hearts"
                        data-item="likes"
                        data-type="like"
                        data-like-href="{{ path('app_article_like', {slug: article.slug, type: 'like'}) }}"
                        data-dislike-href="{{ path('app_article_like', {slug: article.slug, type: 'dislike'}) }}"
                    ><span data-item="likesCount">{{ article.likeCount }}</span> <i class="far fa-heart text-danger"></i></div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-12 mt-2 mb-4">
        {{ article.body|cached_markdown }}
    </div>


    <div class="col-sm-12 mb-4">
        <h3><i class="pr-3 far fa-comment text-secondary"></i>{{ article.nonDeletedComments|length }} Комментария</h3>
        <hr>

        <div class="row mb-4">
            <div class="col-sm-12">
                <div class="comment-container align-self-start col-sm-6">
                    <div class="form-group">
                        <textarea class="form-control" rows="2"></textarea>
                    </div>
                    <button type="submit" class="btn btn-info">Комментировать</button>
                </div>
            </div>
        </div>

        {% for comment in article.nonDeletedComments %}
            <div class="row mt-2">
                <div class="col-sm-12">
                    <div class="media">
                        <img class="align-self-start comment-img rounded-circle" src="{{ asset('images/cat-profile.png') }}">
                        <div class="media-body align-self-start col-sm-6">
                            <b>{{ comment.authorName }}</b>
                            <small>{{ comment.createdAt|ago }} {% if comment.deletedAt %} DELETED {% endif %}</small>
                            <br>
                            <span class="comment">{{ comment.content }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}